repos:
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 23.9.1
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]

  - repo: https://github.com/hakancelikdev/unimport
    rev: 1.0.0
    hooks:
      - id: unimport
        args: [--remove, --include-star-import]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
      - id: mypy
        exclude: docs
        args:
          [
            --ignore-missing-imports,
            --show-error-codes,
            --disallow-incomplete-defs,
            --explicit-package-bases,
          ]
        additional_dependencies: [types-toml==0.1.3]

  - repo: https://github.com/PyCQA/docformatter
    rev: v1.7.5
    hooks:
      - id: docformatter
        args: [--in-place]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3
    hooks:
      - id: prettier
        args: [--prose-wrap=always, --print-width=88]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
        files: "\\.(py|.txt|.yaml|.json|.in|.md|.toml|.cfg|.html|.yml)$"
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-yaml
      - id: trailing-whitespace
